# Generated by Django 5.0.6 on 2024-07-03 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GalleryImages', to='galleries.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='video_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GalleryVideos', to='galleries.gallery')),
            ],
        ),
    ]
