# Generated by Django 5.0.6 on 2024-07-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('subjects', models.CharField(max_length=100, verbose_name='Пердмет')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождение')),
                ('experiance', models.IntegerField(blank=True, null=True, verbose_name='Опыт в годах:')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher_images/', verbose_name='Фотографии')),
            ],
        ),
    ]
