# Generated by Django 5.0.6 on 2024-07-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Математика', 'Математика'), ('Физика', 'Физика'), ('Химия', 'Химия'), ('Биология', 'Биология'), ('История', 'История'), ('География', 'География'), ('Английский язык', 'Английский язык'), ('Физическая культура', 'Физическая культура'), ('Музыка', 'Музыка'), ('ИЗО', 'ИЗО'), ('Русский язык', 'Русский язык'), ('Литература', 'Литература'), ('Кыргыз тил', 'Кыргыз тил'), ('Адабият', 'Адабият'), ('ДПМ', 'ДПМ')], max_length=50)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='grades.grade')),
            ],
        ),
    ]
