# Generated by Django 5.0.6 on 2024-07-10 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Математика'), ('Physics', 'Физика'), ('Chemistry', 'Химия'), ('Biology', 'Биология'), ('History', 'История'), ('Geography', 'География'), ('English', 'Английский язык'), ('Physical Education', 'Физическая культура'), ('Music', 'Музыка'), ('Art', 'ИЗО')], max_length=50)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='grades.grade')),
            ],
        ),
    ]
